### ISSUE TITLE
creating a second minikube cluster fails

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-minikube#22]
On Linux Fedora 39:

When a minikube cluster is already present, trying to create a second cluster (`cluster2`) fails:

Error: Failed to create minikube cluster. E1214 11:29:20.609632 515384 cache.go:189] Error downloading kic artifacts: not yet implemented, see issue #8426 E1214 11:29:20.791061 515384 network_create.go:113] error while trying to create podman network cluster2 192.168.49.0/24: create podman network cluster2 192.168.49.0/24 with gateway 192.168.49.1 and MTU of 0: podman network create --driver=bridge --subnet=192.168.49.0/24 --gateway=192.168.49.1 --label=created_by.minikube.sigs.k8s.io=true --label=name.minikube.sigs.k8s.io=cluster2 cluster2: exit status 125 stdout: stderr: Error: subnet 192.168.49.0/24 is already used on the host or by another config ! Impossible de créer un réseau dédié, cela peut entraîner une modification de l'adresse IP du cluster après le redémarrage : un-retryable: create podman network cluster2 192.168.49.0/24 with gateway 192.168.49.1 and MTU of 0: podman network create --driver=bridge --subnet=192.168.49.0/24 --gateway=192.168.49.1 --label=created_by.minikube.sigs.k8s.io=true --label=name.minikube.sigs.k8s.io=cluster2 cluster2: exit status 125 stdout: stderr: Error: subnet 192.168.49.0/24 is already used on the host or by another config ! l'initialisation a échoué, va réessayer : wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1 stdout: stderr: unable to select an IP from lo network interface To see the stack trace of this error execute with --v=5 or higher * X Erreur lors du démarrage du cluster: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1 stdout: stderr: unable to select an IP from lo network interface To see the stack trace of this error execute with --v=5 or higher * ╭────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ * Si les conseils ci-dessus ne vous aident pas, veuillez nous en informer : │ │ https://github.com/kubernetes/minikube/issues/new/choose │ │ │ │ * Veuillez exécuter `minikube logs --file=logs.txt` et attachez logs.txt au problème GitHub. │ │ │ ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯ X Fermeture en raison de GUEST_START : failed to start node: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1 stdout: stderr: unable to select an IP from lo network interface To see the stack trace of this error execute with --v=5 or higher * ╭────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ * Si les conseils ci-dessus ne vous aident pas, veuillez nous en informer : │ │ https://github.com/kubernetes/minikube/issues/new/choose │ │ │ │ * Veuillez exécuter `minikube logs --file=logs.txt` et attachez logs.txt au problème GitHub. │ │ │ ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by jeffmaury** [comment]
Works on Windows. Would be good to check if it's working with the minikube CLI.

Also should be reported to https://github.com/containers/podman-desktop-extension-minikube

**Comment by lstocchi** [comment]
Facing the same error on Windows. In my case this is the first cluster i'm creating

**Comment by jeffmaury** [comment]
I just created a Minikube cluster on Win11Pro. Using minikube 1.32.0 and Podman 4.9.4. Will check with Podman 5

**Comment by jeffmaury** [comment]
I can create several clusters on Win11Pro and Podman 5.0.2

**Comment by jeffmaury** [comment]
Seems minikube requires a rootful machine now

**Comment by lstocchi** [comment]
Just tried again with the rootful machine i had and it worked. I'm puzzled. I'm pretty sure i also did the same things when I was working on the kubernetes demo and it didn't work....

**Comment by lstocchi** [comment]
@jeffmaury can you please try by having the default machine stopped, then another one running? 
I face the issue in this way. Then if i go to the dashboard i can see the minikube instance created though :/ 

![image](https://github.com/containers/podman-desktop-extension-minikube/assets/49404737/1888934c-ee4b-46f8-9dab-84c5b1378885)

**Comment by jeffmaury** [comment]
Is your second machine the default one. I think the minikube podman driver is using the default connection

**Comment by lstocchi** [comment]
> Is your second machine the default one. I think the minikube podman driver is using the default connection

yes, it was the default one but the problem seems to be the network created by podman. It keeps using the same subnet and it fails. Now i have both the default and the other machine running, i created two cluster on the default connection and it failed on the second creation.

**Comment by feloy** [comment]
On Fedora 40, I now have another error, but the error also happens when trying to start the clusters from the CLI. I guess I can close the issue as the problem comes from minikube itself
