### ISSUE TITLE
Not able to create a minikube cluster

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-minikube#4]
I'm able to click on the minikube in status bar, it downloads and install into my system minikube but I don't see in resource view a way to create a minikube cluster

**Comment by mikhey** [comment]
Just tried this with Podman Desktop v1.4.0 and I can confirm that Minikube does not display in the Settings > Resources tab in addition I have no status bar prompting for the installation of Minikube CLI - I just used winget to install it.
