### ISSUE TITLE
Failed minikube system wide installation on Fedora 40

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-minikube#42]
I have installed minikube 0.3.0 extension on podman desktop (1.10.2) and now I would like to install the binary:
![minikube_failed_install_fedora_system_wide](https://github.com/containers/podman-desktop/assets/19164299/00d9e730-
de07-4848-bca6-5f4245379a79)

Console log:
```
main ↪️ [minikube] Made /home/odockal/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.minikube/minikube-linux-amd64 executable
VM5:2 main ↪️ [minikube] Failed to install 'minikube' binary: Command execution failed with exit code 1: Command execution failed with exit code 1
console.<computed> @ VM5:2
VM5:2 main ↪️ [minikube] Command execution failed with exit code 1: Command execution failed with exit code 1
    at ChildProcess.<anonymous> (/app/lib/io.podman_desktop.PodmanDesktop/resources/app.asar/packages/main/dist/index.cjs:336:13044)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
console.<computed> @ VM5:2
VM5:2 main ↪️ [minikube] Error: Portal call failed: Failed to start command: Failed to execute child process “minikube-linux-amd64” (No such file or directory)

    at ChildProcess.<anonymous> (/home/odockal/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionminikube/dist/extension.js:132:16)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12)
console.<computed> @ VM5:2
2VM5:2 main ↪️ [minikube] minikube extension is active
```

**Comment by dc-me** [comment]
I run into the same problem on fedora 40
```
if ((system === 'linux' || system === 'darwin') && !fs.existsSync(localBinDir)) {
    if (system === 'darwin') {
      args.unshift('mkdir', '-p', localBinDir, '&&');
    } else {
      // add mkdir -p /usr/local/bin just after the first item or args array (so it'll be in the -c shell instruction)
      args[args.length - 1] = `mkdir -p /usr/local/bin && ${args[args.length - 1]}`;
    }
  }
```
the code must run into this condition, but the local bin dir does exist, anyway with manual cp it works.

**Comment by odockal** [comment]
> I run into the same problem on fedora 40
> 
> ```
> if ((system === 'linux' || system === 'darwin') && !fs.existsSync(localBinDir)) {
>     if (system === 'darwin') {
>       args.unshift('mkdir', '-p', localBinDir, '&&');
>     } else {
>       // add mkdir -p /usr/local/bin just after the first item or args array (so it'll be in the -c shell instruction)
>       args[args.length - 1] = `mkdir -p /usr/local/bin && ${args[args.length - 1]}`;
>     }
>   }
> ```
> 
> the code must run into this condition, but the local bin dir does exist, anyway with manual cp it works.

I have tried to debug the code and you are right. Even though the directory exists, the function `fs.existsSync(localBinDir)` returns false. 
What is totally puzzling me is that if I try the same check on the cli via node, it correctly returns true. It might be a problem with a permission when called from an extension.

Also, `args[args.length - 1] = `mkdir -p /usr/local/bin && ${args[args.length - 1]}`;` is wrong, as it adds a command `mkdir` where arguments for `cp` are expected.
