### ISSUE TITLE
Deploying to of a container/pod to a Kubernetes Error: read ECONNRESET

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-minikube#45]
I have minikube cluster started via Podman Desktop 1.10.3 with 0.0.3 minikube extension.
I have managed to create a minikube cluster, but any of my attempts to deploy any container or pod to the cluster fails on: `Error: read ECONNRESET`. Without any other specific error stack trace.

If I switch a kubecontext to a minikube, I can see this in console:
```
main ↪️ Error while fetching API groups: Error: read ECONNRESET
main ↪️ Kube pod watch ended Error: read ECONNRESET
```
On cli using kubectl:
```
kubectl get pods -A
E0528 08:59:59.485001 1125359 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:45563/api?timeout=32s": read tcp 127.0.0.1:34034->127.0.0.1:45563: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:34020->127.0.0.1:45563: read: connection reset by peer
```

**Comment by odockal** [comment]
I am able to reproduce the issue now:
The problem is that I tried to restart minikube cluster using Podman Desktop which led to a situation, where it seems on PD side that everything is fine, the status of the cluster is `RUNNING`, but the truth is that it is not. 
1. Start up Minikube cluster
2. Assert it is started
3. Switch context to the minikube
4. Test `kubectl get pods -A` via cli
5. Restart minikube using Podman Desktop
6. Assert: Minikube is started
7. Check `kubectl ...`
Actual result:
```
kubectl get pods -A
Get "https://127.0.0.1:42373/api/v1/pods?limit=500": read tcp 127.0.0.1:35198->127.0.0.1:42373: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:35192->127.0.0.1:42373: read: connection reset by peer
```
Then if you try to deploy to kubernetes, you get `ERROR: ECONNRESET`.

**Comment by slemeur** [comment]
Should we reopen it @odockal ?

**Comment by odockal** [comment]
@slemeur Afaik the fix was never released. If we release the extension with fix, it should be good then.

**Comment by odockal** [comment]
We have epic opened: https://github.com/containers/podman-desktop-extension-minikube/issues/148, maybe we just need to give it more priority.

**Comment by slemeur** [comment]
Ok - thanks!

**Comment by odockal** [comment]
Not sure about windows and Mac, but on Linux this does not happen at all with 0.4.0.
