### ISSUE TITLE
Minikube extension prompts not appearing

### ISSUE THREAD

**Issue by msilmser** [containers/podman-desktop-extension-minikube#9]
### Bug description

After successfully installing the minikube extension, the prompts to no appear in the status bar to install minikube CLI: https://podman-desktop.io/docs/kubernetes/minikube/installing-minikube 

### Operating system

Windows 11 Pro

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Go to  Settings > Extensions.
2. Install the Minikube extension:
- Go to Install a new extension from OCI Image
- Enter the Name of the Image: ghcr.io/containers/podman-desktop-extension-minikube
- Click  Install extension from the OCI image

Expecation is that the minikube appears in the status bar to prompt installation of CLI, but nothing appears.

### Relevant log output

```shell
main ↪️ Activating extension (podman-desktop.minikube)
main ↪️ Activating extension (podman-desktop.minikube) ended
```

### Additional context

![image](https://github.com/containers/podman-desktop/assets/32716062/2c036ddb-94a2-46a6-98c4-052a5f7ea182)

Attempted to restart podman-desktop, remove and re-add extension, disable and re-enable extension but no change with any action.

**Comment by afbjorklund** [comment]
Is it possible that you have already installed the `minikube` binary in your PATH ?

If you do, it magically disappears from the Podman Desktop UI (unlike "Compose")

**Comment by msilmser** [comment]
i do not have minikube installed in any paths. any other possible explanation? happy to test anything or verify.

**Comment by afbjorklund** [comment]
As far as I know, it first checks if `minikube version` is happy and if so that means it is available - thus no button.

Otherwise it checks with the github repository, for a release: https://github.com/kubernetes/minikube/releases

**Comment by afbjorklund** [comment]
Hmm, it could be that I missed the DOS extension.

`const WINDOWS_X64_ASSET_NAME = 'minikube-windows-amd64';`

When I coped it from the kind extension (that doesn't have one)

`const WINDOWS_X64_ASSET_NAME = 'kind-windows-amd64';`
